import { Container, Text } from '@nextui-org/react'
import Head from 'next/head'
import { motion } from 'framer-motion'
import { getProjects } from '../apollo/projects'
import { client } from '../apollo'
import ReactMarkdown from 'react-markdown'
import { GradientText } from '../components/atoms/gradientText'
import { ProjectList } from '../components/organism/projectList'


export default function Home({ projects }) {

  return (
    <div>
      <Head>
        <title>Raymond&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid className="container">
        <motion.div
          initial={{ x: "100%" }}
          animate={{ x: "0" }}
          transition={{ type: "spring", stiffness: 100, duration: 20 }}
        >
          <GradientText h1>
            Raymond
          </GradientText>
        </motion.div>
        <motion.div
          initial={{ x: "-100%" }}
          animate={{ x: "0" }}
          transition={{ type: "spring", stiffness: 100, duration: 20 }}
        >
          <GradientText h1 color="orange">
            Jones
          </GradientText>
          <Text size={'$4xl'}>
            Im a junior Frontend developer with a strong passion for everything IT related🤓.
            I could design and improve both the UI and UX with the help of my knowledges in HTML, CSS and JavaScript🎨.
            Im fluent in both Swedish and English🇸🇪.
            In my spare time I play both video games and football⚽️.
          </Text>
        </motion.div>
        <ProjectList test='hello' projects={projects} />
      </Container>
    </div>
  )
}

export async function getStaticProps() {
  const response = await client.query({
    query: getProjects,
  })
  console.log('RESPONSE (Server side):')

  const arr = response.data.projects

  return {
    props: {
      projects: response.data.projects,
    }
  }
}
